version: '3'

services:
  notebooks:
    build: .
   # if running terminal in jupyter notebook, sudo with user as root gives the capabilities to download other modules
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes
    user: root
    # copies all files in the below directories to the associated directories in docker
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./data:/home/jovyan/data
      - ./data_sample:/home/jovyan/data_sample
      - ./dependencies:/home/jovyan/dependencies
      #  ./dependencies:/home/jovyan/work is created by default from referenced container images
      - ./check_kaggledotjson.sh:/home/jovyan/check_kaggledotjson.sh
    ports:
      - 8888:8888
    command:
        - check_kaggledotjson.sh
#      command: "start-notebook.sh \
#        --NotebookApp.password=${KAGGLE_API_KEY} \